#### 홈페이지 주소 https://www.kaggle.com/datasets/gauravtopre/bank-customer-churn-dataset

## 1. 데이터 불러오기

In [1]:
# 시각화 라이브러리 불러오기 및 한글화
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

# 오류제거
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
# About Dataset
# This dataset is for ABC Multistate bank with following columns:

# customer_id, unused variable.
# credit_score, used as input.
# country, used as input.
# gender, used as input.
# age, used as input.
# tenure, used as input.
# balance, used as input.
# products_number, used as input.
# credit_card, used as input.
# active_member, used as input.
# estimated_salary, used as input.
# churn, used as the target. 1 if the client has left the bank during some period or 0 if he/she has not.

In [3]:
# 데이터 불러오기
df = pd.read_csv("../data/고객이탈데이터.csv")
df

,고객 ID,신용점수,국가,성별,나이,근속기간,계좌잔액,사용중인상품수,신용카드보유여부,활성회원여부,추정연봉,고객이탈여부
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   고객 ID     10000 non-null  int64
 1   신용점수      10000 non-null  int64
 2   국가        10000 non-null  object
 3   성별        10000 non-null  object
 4   나이        10000 non-null  int64
 5   근속기간      10000 non-null  int64
 6   계좌잔액      10000 non-null  float64
 7   사용중인상품수   10000 non-null  int64
 8   신용카드보유여부  10000 non-null  int64
 9   활성회원여부    10000 non-null  int64
 10  추정연봉      10000 non-null  float64
 11  고객이탈여부    10000 non-null  int64
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB

# 2. 데이터전처리

### 2.1 불필요한 데이터 삭제

In [5]:
# customer_id 삭제
df.drop('고객 ID',axis=1,inplace=True)

### 2.2 문자열 숫자화(label Encoding)

In [6]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

# 국가데이터 학습 
country_data = label_encoder.fit_transform(df["국가"])
print(country_data)

# 성별데이터 학습 
gender_data = label_encoder.fit_transform(df["성별"])
print(gender_data)

# 데이터 변환
df["국가"] = country_data
df["성별"] = gender_data


df

[0 2 0 ... 0 1 0]
[0 0 0 ... 0 1 0]

,신용점수,국가,성별,나이,근속기간,계좌잔액,사용중인상품수,신용카드보유여부,활성회원여부,추정연봉,고객이탈여부
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [10]:
df.to_csv("../data/전처리완료.csv",index=False)

# 3. 모델링

### 3.1 데이터 분리

In [7]:
# 데이터 분리 라이브러리
from sklearn.model_selection import train_test_split

# 특징 변수(X)와 목표 변수(y) 분리
X = df.drop('고객이탈여부', axis=1)
y = df['고객이탈여부']

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

      신용점수  국가  성별  나이  근속기간       계좌잔액  사용중인상품수  신용카드보유여부  활성회원여부       추정연봉
9254   686   0   1  32     6       0.00        2         1       1  179093.26
1561   632   1   1  42     4  119624.60        2         1       1  195978.86
1670   559   2   1  24     3  114739.92        1         1       0   85891.02
6087   561   0   0  27     9  135637.00        1         1       0  153080.40
6669   517   0   1  56     9  142147.32        1         0       0   39488.04
...    ...  ..  ..  ..   ...        ...      ...       ...     ...        ...
5734   768   0   1  54     8   69712.74        1         1       1   69381.05
5191   682   0   0  58     1       0.00        1         1       1     706.50
5390   735   0   0  38     1       0.00        3         0       0   92220.12
860    667   0   1  43     8  190227.46        1         1       0   97508.04
7270   697   1   1  51     1  147910.30        1         1       1   53581.14

[8000 rows x 10 columns]

### 3.2 연속형 데이터 정규화

In [9]:
# 연속형 데이터 정규화
from sklearn.preprocessing import StandardScaler

# 연속형 열 선택
numeric_features = ['신용점수', '나이', '계좌잔액', '근속기간', '추정연봉']

# 정규화 객체 생성
scaler = StandardScaler()


# 훈련데이터에 수치형 데이터 정규화
X_train[numeric_features] = scaler.fit_transform(X_train[numeric_features])

# test data를 훈련데이터에 맞게 정규화 적용
X_test[numeric_features] = scaler.transform(X_test[numeric_features])

# 결과 출력
X_train

,신용점수,국가,성별,나이,근속기간,계좌잔액,사용중인상품수,신용카드보유여부,활성회원여부,추정연봉
9254,0.356500,0,1,-0.655786,0.345680,-1.218471,2,1,1,1.367670
1561,-0.203898,1,1,0.294938,-0.348369,0.696838,2,1,1,1.661254
1670,-0.961472,2,1,-1.416365,-0.695393,0.618629,1,1,0,-0.252807
6087,-0.940717,0,0,-1.131148,1.386753,0.953212,1,1,0,0.915393
6669,-1.397337,0,1,1.625953,1.386753,1.057449,1,0,0,-1.059600
...,...,...,...,...,...,...,...,...,...,...
5734,1.207474,0,1,1.435808,1.039728,-0.102301,1,1,1,-0.539860
5191,0.314989,0,0,1.816097,-1.389442,-1.218471,1,1,1,-1.733882
5390,0.865009,0,0,-0.085351,-1.389442,-1.218471,3,0,0,-0.142765
860,0.159323,0,1,0.390011,1.039728,1.827259,1,1,0,-0.050826
7270,0.470655,1,1,1.150590,-1.389442,1.149720,1,1,1,-0.814568